### ISSUE TITLE
Coverage is reset when a file is re-sourced

### ISSUE THREAD

**Issue by varingst** [Vimjas/covimerage#63]
A minimal example:

```
" plugin/foo.vim:
fun! foo#foo()
  return 'foo'
endfun
```
```
" test/plugin/foo.vader:
Before:
  runtime plugin/foo.vim
Execute:
  AssertEqual 'foo', foo#foo()
Execute:
  AssertEqual 1, 1
```
Even though `return 'foo'` is covered by the first `Execute` block, since `plugin/foo.vim` is re-sourced before the next execute block, that status is wiped. The coverage report only covers what was tested after the last time `plugin/foo.vim` was sourced.

**Comment by blueyed** [comment]
Thanks for the report.

This is a limitation of Vim's coverage reporting itself.

You should avoid `runtime` for that reason, but if required (e.g. because you monkeypatched something etc) run it in separate/isolated cases/suites (where it becomes unnecessary then for resetting/reloading things).

With Neomake I have a set of isolated tests, which get run separately, and coverage then gets combinded: https://github.com/neomake/neomake/tree/master/tests/isolated
For this you can use `covimerage run --append`.
For reference: https://github.com/neomake/neomake/blob/7f834152836166f533ab4944792c6d0087d60f5a/Makefile#L132-L139

**Comment by blueyed** [comment]
Closing, but feel free to follow up of course.
